### ISSUE TITLE
Chest loot only shows mod name, not structure

### ISSUE THREAD

**Issue by theboo** [unilock/EMI_loot#2]
as seen in the image below, the chest loot section is kinda un-usable. Most structure mods seem to have very long names, so all you can see here is the mod's name and it never makes it to the structure name. I would expect to be able to hover over the text to expand but that does not seem to be that case. I do not know if this is an issue with the fabric version of the mod, i dont use fabric and do not have the time to load up a fabric instance and test.

![image](https://github.com/unilock/EMI_loot/assets/3585761/b0c2a36c-1e34-4af7-92c0-7b900eb2913d)

**Comment by theboo** [comment]
nevermind, looks like it doesnt have structure name anyway. Likely not your issue but an issue with the current implementation of EMI loot Fabric. This tab is very useful for vanilla, but in packs with single mods like repurposed structures that have dozens of structures and hundreds of chest locations, "repurposed structures loot chest" isnt exactly valuable haha.

**Comment by unilock** [comment]
To quote fzzyhmstrs (EMI Loot's author) from the relevant discussion in [Emi's Discord guild](https://discord.gg/T2PuD9RTWV):

> There is no canonical loot table translation, but I did include my own in EMI Loot, so you can use the following in lang: `emi_loot.[table_type].[loot table identifier]`, for example `emi_loot.chest.yourMod:chests/cool_dungeon_loot`

([source](https://discord.com/channels/527336258339340289/984252821601919016/1174339939446554718))

Since this concerns upstream EMI Loot rather than the Architectury / Forge port specifically (and since it appears to be more or less resolved), I'll be closing this issue.
